### ISSUE TITLE
Invalid DOI error

### ISSUE THREAD

**Issue by twsh** [jgilchrist/pybib#2]
I tried to run pybib with your examples. It works fine from the command line. But when I put them in a file 'foo.doi' and do `$ bib -f foo.doi` I get error messages like: 'Line 1: Invalid DOI 10.1145/2043164.2018477'. This is, of course, a valid DOI. I'm using the latest version installed with Pip3 on Yosemite.

**Comment by jgilchrist** [comment]
Hi @twsh, sorry you're having problems!

Could you please post the contents of the file you're using?

**Comment by twsh** [comment]
I tried it with the example from your Reddit post:

```
network_failures        10.1145/2043164.2018477
comp_sci_ubiq           10.1145/159544.159617

```

Which is odd because presumably that works fine for you. And the DOI is says is invalid isn't, and works as `$ bib 10.1145/2043164.2018477`.

**Comment by jgilchrist** [comment]
I updated the regular expression which matches DOIs relatively recently - the new version is evidently a little broken.

I'm about to push a fix as v1.2.2, could you please try it out and let me know if it fixes your problem?

**Comment by twsh** [comment]
Great! The new version fixes the problem.

**Comment by jgilchrist** [comment]
Fantastic, thank you! If you've got any more problems/suggestions feel free to open another issue.
